languageCode = "id"
languageName = "Indonesia"
weight = 1
title = "Utrodus Said"

[params]
displayName = "Indonesia"
isoCode = "id"
rtl = false
dateFormat = "2 January 2006"
logo = "utrodus_logo_dark.png"
secondaryLogo = "utrodus_logo_light.png"

[author]
image = "utrodus_w8ad5s.webp"
name = "Utrodus Said Al Baqi"
headline = "Software Engineer"
bio = "Software Engineer yang Berfokus pada Aplikasi Multi-Platform dengan Dart dan Flutter"