languageCode = "id"
languageName = "Indonesia"
weight = 1
title = "Utrodus Said"

[params]
displayName = "ID"
isoCode = "id"
rtl = false
dateFormat = "2 January 2006"
logo = "utrodus_logo_dark.png"
secondaryLogo = "utrodus_logo_light.png"

[author]
image = "utrodus_w8ad5s.webp"
name = "Utrodus Said Al Baqi"
headline = "Flutter Developer | Flutter Engineer"
bio = "Saya bersemangat mengembangkan aplikasi Cross-platform yang berdampak. Dengan pengalaman lebih dari 3 tahun, saya mahir dalam Dart & Flutter."