languageCode = "en"
languageName = "English"
weight = 1
title = "Utrodus Said"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "utrodus_logo_dark.png"
secondaryLogo = "utrodus_logo_light.png"

[author]
image = "utrodus_w8ad5s.webp"
name = "Utrodus Said Al Baqi"
headline = "Flutter Developer | Flutter Engineer"
bio = "I'm passionate about developing impactful cross-platform apps. With 3+ years of experience, I am proficient in Dart & Flutter"
