languageCode = "id"
languageName = "Indonesia"
weight = 1
title = "Utrodus Said"

[params]
displayName = "ID"
isoCode = "id"
rtl = false
dateFormat = "2 January 2006"
logo = "utrodus_logo_dark.png"
secondaryLogo = "utrodus_logo_light.png"

[author]
image = "utrodus_w8ad5s.webp"
name = "Utrodus Said Al Baqi"
headline = "Flutter Developer | Flutter Engineer"
bio = "Dart & Flutter enthusiast dengan pengalaman lebih dari 3 tahun dalam mengembangkan aplikasi yang indah, fungsional, dan ramah pengguna."
links = [ { github = "https://github.com/utrodus" }, { linkedin = "https://www.linkedin.com/in/utrodus-said/" }, { telegram = "https://t.me/said_albaqi" },  { instagram = "https://www.instagram.com/utrodus/" }, { youtube = "https://www.youtube.com/@utrodus" } ]
