languageCode = "id"
languageName = "Indonesia"
weight = 1
title = "Flutter Developer | Flutter Engineer | Cross-platform Apps | Utrodus Said Al Baqi"

[params]
displayName = "ID"
isoCode = "id"
rtl = false
dateFormat = "2 January 2006"
logo = "utrodus_logo_dark.png"
secondaryLogo = "utrodus_logo_light.png"

[author]
image = "utrodus.png"
name = "Utrodus Said Al Baqi"
headline = "Flutter Developer | Flutter Engineer"
bio = "Flutter Developer dengan pengalaman lebih dari 3 tahun dalam mengembangkan aplikasi yang fungsional dan ramah pengguna."
links = [ { github = "https://github.com/utrodus" }, { linkedin = "https://www.linkedin.com/in/utrodus-said/" }, { telegram = "https://t.me/said_albaqi" },  { instagram = "https://www.instagram.com/utrodus/" }, { youtube = "https://www.youtube.com/@utrodus" } ]
