languageCode = "id"
languageName = "Indonesia"
weight = 1
title = "Utrodus Said Al Baqi | Flutter Developer | Flutter Engineer | Cross-platform Apps"

[params]
displayName = "Indonesia"
isoCode = "id"
rtl = false
dateFormat = "2 January 2006"
logo = "utrodus_logo_dark.webp"
secondaryLogo = "utrodus_logo_light.png"
description = "Jelajahi portofolio Utrodus Said Al Baqi—Flutter developer dan engineer berpengalaman. Spesialis dalam pengembangan aplikasi lintas platform (Cross-platform) dengan Flutter. Hubungi sekarang untuk hire Flutter engineer expert untuk proyek Anda!"

[author]
image = "utrodus_profile.webp"
name = "Utrodus Said Al Baqi"
headline = "Flutter Developer | Software Engineer | Cross-platform"
bio = "With over 4 years of experience in Flutter app development, I specialize in creating user-focused mobile applications that boost engagement and drive business profitability."
links = [ { github = "https://github.com/utrodus" }, { linkedin = "https://www.linkedin.com/in/utrodus-said/" }, { telegram = "https://t.me/said_albaqi" },  { instagram = "https://www.instagram.com/utrodus/" }, { youtube = "https://www.youtube.com/@utrodus" } ]
