[[main]]
name = "Tentang"
pageRef = "/about"
identifier = "ZsZOuvAcPO"
weight = 3

[[main]]
name = "Blog"
pageRef = "/posts"
identifier = "M65aSqWxzz"
weight = 1

[[main]]
name = "Portfolio"
pageRef = "/portfolio"
identifier = "WVOjONkwdt"
weight = 2

[[main]]
pre = "link"
name = "Resume"
url = "https://drive.google.com/file/d/1Jh6jWzEFOGR5PFBhW7iHwcUk9wYr-fF-/view?usp=drive_link"
identifier = "SzfrNuNCmZ"
weight = 4

[[main]]
pre = "github"
url = "https://github.com/utrodus"
identifier = "a2y3RYhNGO"
weight = 100

[[main]]
pre = "linkedin"
url = "https://www.linkedin.com/in/utrodus-said/"
identifier = "ghzZP893da"
weight = 200





[[footer]]
none = "none"

