[[main]]
name = "Portfolio"
pageRef = "/portfolio"
identifier = "WVOjONkwdt"
weight = 1

[[main]]
name = "Blog"
pageRef = "/posts"
identifier = "M65aSqWxzz"
weight = 3

[[main]]
name = "About"
pageRef = "/about"
identifier = "ZsZOuvAcPO"
weight = 2

[[main]]
name = "Hire Me"
pageRef = "/hire-me"
identifier = "hire-me"
weight = 4

[[main]]
pre = "github"
url = "https://github.com/utrodus"
identifier = "a2y3RYhNGO"
weight = 6

[[main]]
pre = "linkedin"
url = "https://www.linkedin.com/in/utrodus-said/"
identifier = "ghzZP893da"
weight = 7

[[main]]
name = "Contact Me"
pre = "email"
url = "mailto:contact.utrodus@gmail.com"
identifier = "9yKxuByokC"
weight = 5

[[footer]]
none = "none"
