[[main]]
name = "Portfolio"
pageRef = "/portfolio"
identifier = "WVOjONkwdt"
weight = 1

[[main]]
name = "Blog"
pageRef = "/posts"
identifier = "M65aSqWxzz"
weight = 2


[[main]]
name = "About"
pageRef = "/about"
identifier = "ZsZOuvAcPO"
weight = 3

[[main]]
name = "Hire Me"
pageRef = "/hire-me"
identifier = "hire-me"
weight = 4


[[main]]
name = "Contact"
pageRef = "/contact"
identifier = "hIDtXPNvpU"
weight = 5


[[main]]
pre = "github"
url = "https://github.com/utrodus"
identifier = "a2y3RYhNGO"
weight = 6

[[main]]
pre = "linkedin"
url = "https://www.linkedin.com/in/utrodus-said/"
identifier = "ghzZP893da"
weight = 7


[[footer]]
none = "none"
