colorScheme = "congo"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
disableImageOptimization = false
disableTextInHeader = false
highlightCurrentMenuArea = true
smartTOC = true
defaultBackgroundImage = "background.png"
mainSections = ["portfolio" ]
secondarySections = ["posts"]

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true
[homepage]
layout = "background"
layoutBackgroundHeaderSpace = true
homepageImage = "background.png"
showRecent = true
showRecentPosts = true
showRecentItems = 3
showRecentPostItems = 3
showMoreLink = true
showMorePostLink = true
showMoreLinkDest = "/portfolio"
showMorePostLinkDest = "/posts"
cardView = true
cardViewPost = false
cardViewScreenWidth = false
layoutBackgroundBlur = true

[article]
showDate = true
showSummary = false
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showAuthorBottom = true
showHero = false
heroStyle = "background" 
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
showZenMode = false
showRelatedContent = true
relatedContentLimit = 3
# sharingLinks = [ "linkedin", "twitter", "reddit", "whatsapp", "telegram", "facebook"]

[list]
showHero = false
heroStyle = "background" 
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
  showTermCount = true
  layoutBackgroundHeaderSpace = false
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = false
  heroStyle = "custom" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
